// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { MerkleRootConfig } from "./tables/MerkleRootConfig.sol";
import { VRGDAConfig, VRGDAConfigData } from "./tables/VRGDAConfig.sol";
import { TileLetter } from "./tables/TileLetter.sol";
import { TilePlayer } from "./tables/TilePlayer.sol";
import { DrawRequest, DrawRequestData } from "./tables/DrawRequest.sol";
import { PlayerLetters } from "./tables/PlayerLetters.sol";
import { DrawLetterOdds } from "./tables/DrawLetterOdds.sol";
import { Treasury } from "./tables/Treasury.sol";
import { Points } from "./tables/Points.sol";
import { Spent } from "./tables/Spent.sol";
import { DrawCount } from "./tables/DrawCount.sol";
import { PlayResult, PlayResultData } from "./tables/PlayResult.sol";
import { PointsClaimed, PointsClaimedData } from "./tables/PointsClaimed.sol";
import { LettersDrawn, LettersDrawnData } from "./tables/LettersDrawn.sol";
import { PointsResult, PointsResultData } from "./tables/PointsResult.sol";
