[fuzz]
  runs = 1028

[profile.redstone-garnet]
  eth_rpc_url = "https://rpc.garnet.qry.live"

[profile.redstone-holesky-legacy]
  eth_rpc_url = "https://rpc.holesky.redstone.xyz"

[profile.lattice-901]
  eth_rpc_url = "https://redstone.linfra.xyz"

[profile.base-testnet]
  eth_rpc_url = "https://goerli.base.org"

[profile.base]
  eth_rpc_url = "https://base-mainnet.blastapi.io"