[fmt]
  sort_imports=true
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[fuzz]
  runs = 1028

[profile.redstone-garnet]
  eth_rpc_url = "https://rpc.garnet.qry.live"

[profile.redstone-holesky-legacy]
  eth_rpc_url = "https://rpc.holesky.redstone.xyz"

[profile.lattice-901]
  eth_rpc_url = "https://redstone.linfra.xyz"

[profile.base-testnet]
  eth_rpc_url = "https://goerli.base.org"

[profile.base-mainnet]
  eth_rpc_url = "https://base-mainnet.blastapi.io"