// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Id } from "./tables/Id.sol";
import { Config, ConfigData } from "./tables/Config.sol";
import { Request, RequestData } from "./tables/Request.sol";
import { Response } from "./tables/Response.sol";
