// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ISetDrawLetterOddsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISetDrawLetterOddsSystem {
    error AlreadySetOdds();
    error InvalidOddsLength();
    error NonzeroFirstValue();

    function words3__setDrawLetterOdds(uint8[] memory odds) external;
}
