// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Letter } from "codegen/common.sol";

/**
 * @title ITransferLettersSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITransferLettersSystem {
  error TransferMissingLetters();

  function words3__transfer(Letter[] memory letters, address to) external;
}
