// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */
enum BonusType {
  MULTIPLY_WORD,
  MULTIPLY_LETTER
}

enum Direction {
  LEFT_TO_RIGHT,
  TOP_TO_BOTTOM
}

enum Status {
  NOT_STARTED,
  STARTED,
  OVER
}

enum Letter {
  EMPTY,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z
}
