// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { DrawCount } from "./tables/DrawCount.sol";
<<<<<<< HEAD
import { DrawLastSold, DrawLastSoldData } from "./tables/DrawLastSold.sol";
=======
>>>>>>> 5b22178 (feat: diamond bonus pattern)
import { DrawLetterOdds } from "./tables/DrawLetterOdds.sol";

import { DrawUpdate, DrawUpdateData } from "./tables/DrawUpdate.sol";
import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { MerkleRootConfig } from "./tables/MerkleRootConfig.sol";
import { PlayUpdate, PlayUpdateData } from "./tables/PlayUpdate.sol";
import { PlayerLetters } from "./tables/PlayerLetters.sol";
import { Points } from "./tables/Points.sol";

import { PointsClaimedUpdate, PointsClaimedUpdateData } from "./tables/PointsClaimedUpdate.sol";
import { PointsUpdate, PointsUpdateData } from "./tables/PointsUpdate.sol";
<<<<<<< HEAD
import { PriceConfig, PriceConfigData } from "./tables/PriceConfig.sol";
=======
>>>>>>> 5b22178 (feat: diamond bonus pattern)
import { Spent } from "./tables/Spent.sol";
import { TileLetter } from "./tables/TileLetter.sol";
import { TilePlayer } from "./tables/TilePlayer.sol";
import { Treasury } from "./tables/Treasury.sol";
import { UpdateId } from "./tables/UpdateId.sol";
<<<<<<< HEAD
=======
import { VRGDAConfig, VRGDAConfigData } from "./tables/VRGDAConfig.sol";
>>>>>>> 5b22178 (feat: diamond bonus pattern)
