// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { MerkleRootConfig } from "./tables/MerkleRootConfig.sol";
import { VRGDAConfig, VRGDAConfigData } from "./tables/VRGDAConfig.sol";
import { TileLetter } from "./tables/TileLetter.sol";
import { TilePlayer } from "./tables/TilePlayer.sol";
import { PlayerLetters } from "./tables/PlayerLetters.sol";
import { Treasury } from "./tables/Treasury.sol";
import { Points } from "./tables/Points.sol";
import { Spent } from "./tables/Spent.sol";
import { LetterCount } from "./tables/LetterCount.sol";
import { Claimed } from "./tables/Claimed.sol";
import { SpentMove } from "./tables/SpentMove.sol";
import { PlayResult, PlayResultData } from "./tables/PlayResult.sol";
import { PointsResult, PointsResultData } from "./tables/PointsResult.sol";
