// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData } from "./tables/GameConfig.sol";
import { FeeConfig, FeeConfigData } from "./tables/FeeConfig.sol";
import { ClaimRestrictionConfig } from "./tables/ClaimRestrictionConfig.sol";
import { MerkleRootConfig } from "./tables/MerkleRootConfig.sol";
import { PriceConfig, PriceConfigData } from "./tables/PriceConfig.sol";
import { DrawLetterOdds } from "./tables/DrawLetterOdds.sol";
import { TileLetter } from "./tables/TileLetter.sol";
import { TilePlayer } from "./tables/TilePlayer.sol";
import { PlayerLetters } from "./tables/PlayerLetters.sol";
import { DrawLastSold, DrawLastSoldData } from "./tables/DrawLastSold.sol";
import { DrawCount } from "./tables/DrawCount.sol";
import { Points } from "./tables/Points.sol";
import { Treasury } from "./tables/Treasury.sol";
import { Spent } from "./tables/Spent.sol";
import { UpdateId } from "./tables/UpdateId.sol";
import { PlayUpdate, PlayUpdateData } from "./tables/PlayUpdate.sol";
import { PointsUpdate, PointsUpdateData } from "./tables/PointsUpdate.sol";
import { PointsClaimedUpdate, PointsClaimedUpdateData } from "./tables/PointsClaimedUpdate.sol";
import { DrawUpdate, DrawUpdateData } from "./tables/DrawUpdate.sol";
