// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigData, GameConfigTableId } from "./tables/GameConfig.sol";
import { MerkleRootConfig, MerkleRootConfigTableId } from "./tables/MerkleRootConfig.sol";
import { VRGDAConfig, VRGDAConfigData, VRGDAConfigTableId } from "./tables/VRGDAConfig.sol";
import { TileLetter, TileLetterTableId } from "./tables/TileLetter.sol";
import { TilePlayer, TilePlayerTableId } from "./tables/TilePlayer.sol";
import { Treasury, TreasuryTableId } from "./tables/Treasury.sol";
import { Points, PointsTableId } from "./tables/Points.sol";
import { Spent, SpentTableId } from "./tables/Spent.sol";
import { LetterCount, LetterCountTableId } from "./tables/LetterCount.sol";
import { Claimed, ClaimedTableId } from "./tables/Claimed.sol";
