// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { TileTable, TileTableData, TileTableTableId } from "./tables/TileTable.sol";
import { LetterWeightTable, LetterWeightTableTableId } from "./tables/LetterWeightTable.sol";
import { RewardsTable, RewardsTableTableId } from "./tables/RewardsTable.sol";
import { ScoreTable, ScoreTableTableId } from "./tables/ScoreTable.sol";
import { SpentTable, SpentTableTableId } from "./tables/SpentTable.sol";
