// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Coord, Letter } from "./../../systems/PlaceTileSystem.sol";

interface IPlaceTileSystem {
  function placeTile(Coord memory coord, address player, Letter letter, int256 daysSinceStart) external;
}
