// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Letter, Direction } from "codegen/Types.sol";
import { Coord } from "common/Coord.sol";
import { Bound } from "common/Bound.sol";

interface IPlaySystem {
  function play(
    Letter[] memory word,
    bytes32[] memory proof,
    Coord memory coord,
    Direction direction,
    Bound[] memory bounds
  ) external payable;
}
