// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Letter } from "codegen/common.sol";

/**
 * @title IStartSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStartSystem {
  function start(
    Letter[] memory initialWord,
    uint256 endTime,
    uint256 maxPlayerSpend,
    bytes32 merkleRoot,
    int256 vrgdaTargetPrice,
    int256 vrgdaPriceDecay,
    int256 vrgdaPerDayInitial,
    int256 vrgdaPower,
    address host,
    uint32 crossWordRewardFraction,
    uint16 hostFeeBps
  ) external;

  function end() external;
}
