// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Letter } from "codegen/Types.sol";

interface IStartSystem {
  function start(
    Letter[] memory initialWord,
    uint16 maxWords,
    bytes32 merkleRoot,
    int256 vrgdaTargetPrice,
    int256 vrgdaPriceDecay,
    int256 vrgdaPerDay,
    uint32 crossWordRewardFraction
  ) external;

  function end() external;
}
