// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Letter } from "codegen/common.sol";
import { FeeConfigData, PriceConfigData } from "codegen/index.sol";

/**
 * @title IStartSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IStartSystem {
    error GameAlreadyStarted();
    error InitialWordTooLong();
    error PriceWadFactorTooSmall();

    function start(
        Letter[] memory initialWord,
        uint32[26] memory initialLetterAllocation,
        address initialLettersTo,
        bytes32 merkleRoot,
        uint256 initialPrice,
        uint256 claimRestrictionDurationBlocks,
        PriceConfigData memory priceConfig,
        FeeConfigData memory feeConfig,
        uint32 crossWordRewardFraction,
        uint16 bonusDistance,
        uint8 numDrawLetters
    )
        external;
}
