// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IClaimSystem } from "./IClaimSystem.sol";
import { IDonateSystem } from "./IDonateSystem.sol";
import { IDrawSystem } from "./IDrawSystem.sol";
import { IPlaySystem } from "./IPlaySystem.sol";
import { ISetDrawLetterOddsSystem } from "./ISetDrawLetterOddsSystem.sol";
import { ISetFeeConfigSystem } from "./ISetFeeConfigSystem.sol";
import { IStartSystem } from "./IStartSystem.sol";
import { ITransferLettersSystem } from "./ITransferLettersSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
    IBaseWorld,
    IClaimSystem,
    IDonateSystem,
    IDrawSystem,
    IPlaySystem,
    ISetDrawLetterOddsSystem,
    ISetFeeConfigSystem,
    IStartSystem,
    ITransferLettersSystem
{ }
